### PR TITLE
Initializing kiosk code for windows platform.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by thaarok** [comment]
Not going to merge until some working part will be included.

**Comment by ghost** [comment]
> Not going to merge until some working part will be included.

My understanding is that there is no windows API currently available to get kiosk mode details or manipulate kiosk mode.
There are two parts to make kiosk mode in windows app. Step 1: Add necessary extensions (windows.aboveLockScreen, etc). Step 2: Manually configure the app as kiosk mode (https://beebom.com/configure-windows-10-kiosk-mode/).

So I think I cannot add any working functionality. I think you can include partial windows support by providing the support of including extensions. Let the documentation stress the lack of support to all the six methods and let documentation show the way to manually configure the kiosk mode.

**Comment by thaarok** [comment]
Is there some reason to include this into the cordova plugin, if it implement nothing?

**Comment by ghost** [comment]
Currently I am building a kiosk application that should support  both Android and UWP. I use your extension since that works awesome.  I want to make this extension support windows as much extend it can (something is better than nothing). Otherwise I need to build another plugin like cordova-plugin-kiosk-windows to support. I want my app to be in kiosk mode always. Only this app will be available to the kiosk user (it is a normal windows user account only for running kiosk app).

I believe many people will encounter the same scenario. The partial support (Partial support in the context of this extension. For me it provides full support since I don't do enterKisokMode or exitKioskMode) will make this app more useful.

**Comment by ghost** [comment]
No activity. Closing the PR.

**Comment by thaarok** [comment]
Once your PR will include some functionality, it is welcome. But pure declaration of windows support without any real support would be counterproductive.

**Pull request closed without merging**
