### PR TITLE
Never finish the app

### PR DESCRIPTION
**Pull request by zhanghuanchong**
Override super's `finish` method.

### CODE REVIEW

**Comment by zhanghuanchong** [comment]
Resolves #63

**Comment by thaarok** [comment]
Thanks! Do you have some idea why is finish() overriding needed? It does not look much clear...

**Comment by zhanghuanchong** [comment]
Some devices' back button will trigger `finish` method, instead of `onKeyDown`, `onKeyUp` or `onBackPressed`, which caused user able to get rid of restriction.

**Comment by zhanghuanchong** [comment]
To be a kiosk app, the `finish` method makes no sense. If it exit kiosk mode, the user is easy to kill it. If developer want to quit app, he has many ways, so `finish` method can be override safely.

**Comment by thaarok** [comment]
Thanks for clarification!

**Pull request merged**
